language: cpp

env:
 - RUN_CTEST='false' FLAGS="-DBUILD_SHARED=OFF -DWITH_INCHI=ON -DWITH_STATIC_INCHI=ON"
 - RUN_CTEST='true' FLAGS="-DPYTHON_BINDINGS=ON -DRUN_SWIG=ON"

compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq swig libeigen3-dev

before_script:
 - mkdir build
 - cd build
 - cmake ${FLAGS} ..

script:
 - make -j2
 - test ${RUN_CTEST} = 'true' && ctest -j 2
